### ISSUE TITLE
サークル概要の編集

### ISSUE THREAD

**Issue by izmth** [FUN-AI/fun-ai.github.io#2]
- 輪講の説明に「資料の要約」を追記する。（論文だけではないということを伝えたい）
- 機械学習コンペの参加について追記する。
- メンバー数とか書く？

**Comment by t4t5u0** [comment]
メンバー数は49人

輪講は、論文だけじゃなくて、本とかもよいって感じでかく？

**Comment by izmth** [comment]
基本データのところで「メンバー数：49人（2020年度）」って感じで書こうか。

「論文や本の要約など、勉強したことをまとめ、サークルメンバに発表する会を実施しています。」みたいな感じが良いんじゃないかなと思ってる。

**Comment by t4t5u0** [comment]
良いと思う
