### ISSUE TITLE
top page をサークル概要に変更する

### ISSUE THREAD

**Issue by t4t5u0** [FUN-AI/fun-ai.github.io#4]
多分こっちのほうが嬉しいので

**Comment by izmth** [comment]
Twitterとかポスターに貼るリンクを https://fun-ai.github.io/about にするのは違う？

**Comment by t4t5u0** [comment]
トップページがポストなのどうなんだろうと思った。対応としてはそれで問題ないと思う

**Comment by t4t5u0** [comment]
とりあえず今はいいや
